### ISSUE TITLE
Config Error in sphinx build

### ISSUE THREAD

**Issue by bheavner** [kids-first/kf-developer-handbook#93]
**Describe the bug**
When I follow the install instructions and run `sphinx-autobuild docs/ build -p 8000` I get an error: 
Configuration error:
There is a programmable error in your configuration file:

The server seems to start, but then after I visit 127.0.0.1:8000, I get a 404 error.

**Additional info**
Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/Users/heavner/Projects/kf-developer-handbook/docs/conf.py", line 53, in <module>
    from recommonmark.parser import CommonMarkParser
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/recommonmark/parser.py", line 6, in <module>
    from CommonMark import DocParser, HTMLRenderer
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/CommonMark/__init__.py", line 3, in <module>
    from CommonMark.CommonMark import HTMLRenderer
  File "/Users/heavner/virtualenv/kf_dev_handbook/lib/python3.9/site-packages/CommonMark/CommonMark.py", line 18, in <module>
    HTMLunescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

**Comment by fiendish** [comment]
Please try `pip install --upgrade recommonmark` first and report back if that fixes this issue.

**Comment by bheavner** [comment]
Yes, thanks for the catch - I did file it in the wrong repo! After some further googling, I found the build worked with Python 3.7 instead of 3.9 (which I was attempting when I did the build). For now, that resolved the issue for me. I don't have a clean py3.9 virtual environment available at the moment for further testing.
